<?php

namespace AppBundle\Repository;

/**
 * GirlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GirlRepository extends \Doctrine\ORM\EntityRepository
{
}
